name: Daily GitHub Skyline with Preview Images

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          LATEST_URL=$(curl -s https://api.github.com/repos/cli/cli/releases/latest \
            | grep "browser_download_url.*linux_amd64.tar.gz" \
            | cut -d '"' -f 4)
          curl -fsSL "$LATEST_URL" -o gh.tar.gz
          tar -xzf gh.tar.gz
          sudo cp gh_*/bin/gh /usr/local/bin

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth setup-git

      - name: Install gh-skyline extension
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh extension install github/gh-skyline

      - name: Generate STL file
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh skyline --full --user brudnak --output skyline-full.stl

      - name: Install Blender
        run: |
          sudo apt update
          sudo apt install blender -y

      - name: Remove old PNGs to force fresh render
        run: |
          rm -f skyline-dark.png skyline-light.png

      - name: Render light/dark skyline images
        run: |
          blender -b -P render_skyline.py -- skyline-full.stl

      - name: Touch files to guarantee Git picks them up
        run: |
          touch skyline-dark.png skyline-light.png

      - name: Commit STL and PNGs if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add skyline-full.stl skyline-dark.png skyline-light.png
          git diff --cached --quiet || git commit -m "🏙️ Auto-update skyline STL and previews - $(date -u)"
          git push
