name: Daily GitHub Skyline

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  generate-skyline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI manually (bypass APT)
        run: |
          curl -fsSL https://github.com/cli/cli/releases/latest/download/gh_2.47.0_linux_amd64.tar.gz -o gh.tar.gz
          tar -xzf gh.tar.gz
          sudo cp gh_*/bin/gh /usr/local/bin

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth setup-git

      - name: Install gh-skyline extension
        run: gh extension install github/gh-skyline

      - name: Generate full GitHub skyline STL
        run: |
          gh skyline --full --output skyline-full.stl

      - name: Commit and push STL
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add skyline-full.stl
          git commit -m "Update full skyline STL - $(date -u)" || echo "No changes to commit"
          git push
